"""add_user_roles_and_refresh_token

Revision ID: 370dbab28538
Revises: 7f72b346974f
Create Date: 2026-03-04 08:55:01.012222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370dbab28538'
down_revision: Union[str, None] = '7f72b346974f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Safely create the enum type for Postgres
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole') THEN CREATE TYPE userrole AS ENUM ('USER', 'ADMIN'); END IF; END $$;")
    
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=True))
    op.add_column('users', sa.Column('refresh_token_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_hash')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
