"""Add fashion taxonomy fields to clothing items

Revision ID: 7f72b346974f
Revises: 989688f790f8
Create Date: 2026-03-04 08:38:44.759030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f72b346974f'
down_revision: Union[str, None] = '989688f790f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_items', sa.Column('category', sa.Enum('TOP', 'BOTTOM', 'OUTERWEAR', 'FOOTWEAR', 'ACCESSORY', 'FULL_BODY', 'UNKNOWN', name='fashioncategory'), nullable=True))
    op.add_column('clothing_items', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('clothing_items', sa.Column('classification_status', sa.Enum('CONFIRMED', 'LOW_CONFIDENCE', 'UNKNOWN', name='classificationstatus'), nullable=True))
    op.add_column('clothing_items', sa.Column('raw_model_output', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothing_items', 'raw_model_output')
    op.drop_column('clothing_items', 'classification_status')
    op.drop_column('clothing_items', 'confidence_score')
    op.drop_column('clothing_items', 'category')
    # ### end Alembic commands ###
