"""Add status and task_id to clothing items

Revision ID: 989688f790f8
Revises: 768ef8cb4e9f
Create Date: 2026-03-04 08:33:36.055933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989688f790f8'
down_revision: Union[str, None] = '768ef8cb4e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_items', sa.Column('status', sa.String(), nullable=True))
    op.add_column('clothing_items', sa.Column('task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothing_items', 'task_id')
    op.drop_column('clothing_items', 'status')
    # ### end Alembic commands ###
