"""add_image_hash_column

Revision ID: e82d0bdbfa3e
Revises: 370dbab28538
Create Date: 2026-03-04 09:31:31.878182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82d0bdbfa3e'
down_revision: Union[str, None] = '370dbab28538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_items', sa.Column('image_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_clothing_items_image_hash'), 'clothing_items', ['image_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clothing_items_image_hash'), table_name='clothing_items')
    op.drop_column('clothing_items', 'image_hash')
    # ### end Alembic commands ###
